# Generated by Django 4.1.7 on 2023-09-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demandeproduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomproduit', models.CharField(max_length=100, null=True)),
                ('prix', models.DecimalField(decimal_places=100, max_digits=100)),
                ('caractere', models.TextField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiente', models.DateField(auto_created=True, null=True, verbose_name="date d'experiention")),
                ('datedepot', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date de depot')),
                ('nom_produit', models.CharField(max_length=100, null=True, verbose_name='le nom du produit')),
                ('typeproduit', models.CharField(max_length=100, verbose_name='le type de produit')),
                ('caractere', models.TextField(null=True, verbose_name='decrire le produit')),
                ('prix', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('applique', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True, verbose_name='nom complet')),
                ('specialite', models.CharField(max_length=200, null=True, verbose_name='votre travail')),
                ('ville', models.CharField(max_length=100, verbose_name='ville habite')),
                ('number', models.BigIntegerField(null=True, verbose_name='Numero de telephone')),
            ],
        ),
    ]
