# Generated by Django 4.1.7 on 2023-09-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astuce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('astuce', models.TextField(null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to=True)),
            ],
        ),
    ]
