# Generated by Django 4.2.5 on 2023-10-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppaypal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='creer',
        ),
    ]
