# Generated by Django 4.1.7 on 2023-09-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeReve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datereve', models.DateTimeField(auto_created=True, verbose_name="l'heure et la date du reve")),
                ('decrire', models.TextField(null=True)),
                ('adress', models.EmailField(blank=True, max_length=254)),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(null=True, verbose_name='Description de reve')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
