# Generated by Django 4.1.7 on 2023-09-02 14:13

import django.contrib.auth.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField(auto_created=True, null=True)),
                ('nom', models.CharField(max_length=200, null=True, verbose_name='votre nom complet')),
                ('number', models.BigIntegerField(null=True, verbose_name='numero de telephone')),
                ('ville', models.CharField(max_length=100, null=True, verbose_name='ville habite')),
                ('modeapprend', models.CharField(choices=[('apprendre en ligne', 'apprendre en ligne'), ('apprendre en presentiel', 'apprendre en presentiel')], default='apprendre en ligne', max_length=100, null=True)),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Academiecours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('image_cours', models.ImageField(blank=True, null=True, upload_to=True)),
                ('deposer_lesson', models.FileField(blank=True, upload_to=True)),
                ('ecrire_lesson', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(blank=True, max_length=200, null=True)),
                ('demande', models.TextField(null=True)),
                ('mode', models.CharField(choices=[('participation en ligne', 'participation en ligne'), ('participation en presentielle', 'participation en presentielle')], default='participation en presentielle', max_length=200)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model),
        ),
    ]
