# Generated by Django 4.1.7 on 2023-09-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(blank=True, max_length=50)),
                ('Description', models.TextField(null=True)),
                ('mode', models.CharField(choices=[('une consultation en ligne', 'une consultation en ligne'), ('une consultation en presentielle', 'une consultation en presentielle')], default='une consultation en ligne', max_length=100)),
                ('temps', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=20)),
                ('adress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('son_but', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
